# Generated by Django 4.2.1 on 2023-06-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gstTasks", "0002_tasks_date_butoir"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
