# Generated by Django 4.2 on 2023-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("adresse", models.TextField(blank=True)),
                ("ville", models.CharField(blank=True, max_length=50)),
                ("pays", models.CharField(blank=True, max_length=50)),
                ("date_de_naissance", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("date_de_creation", models.DateTimeField(auto_now_add=True)),
                ("date_de_modification", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(editable=False, unique=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-nom"],
            },
        ),
    ]
