# Generated by Django 4.2 on 2023-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gstContact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="image_prfl",
            field=models.ImageField(
                blank=True,
                default="profiles/default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
