# Generated by Django 4.1.7 on 2023-03-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstPhotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['-nom'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
