# Generated by Django 4.1.7 on 2023-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstDocuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.TextField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
