# Generated by Django 4.2 on 2023-04-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gstNotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_note_cat",
            field=models.ImageField(
                blank=True, default="notes/note.png", null=True, upload_to="notes/"
            ),
        ),
    ]
