# Generated by Django 4.2 on 2023-04-20 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gstRappels", "0002_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(default=datetime.date, null=True),
        ),
    ]
